/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and issue a session token.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session token (idempotent).
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current principal (logged-in username, or the API key name).
         *
         *     ``role`` + ``can_write`` let the console hide write controls for a viewer.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_auth_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_auth_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Password */
        post: operations["set_password_api_auth_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/config/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fleet Trust
         * @description The persisted fleet-wide inbound trust config (FleetSettings singleton).
         */
        get: operations["get_fleet_trust_api_fleet_config_trust_get"];
        put?: never;
        /**
         * Set Fleet Trust
         * @description Persist the fleet trust config and push the EFFECTIVE list to every enabled
         *     node's /api/config/trust. ``enabled=false`` => allow-all pushed (empty list),
         *     but the saved list is kept for the UI. Control-plane only — never touches a
         *     call.
         */
        post: operations["set_fleet_trust_api_fleet_config_trust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/ingest/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Stats
         * @description Worker → controller stats push (opt-in, additive; poll is the fallback).
         *
         *     Resolves the poster to a node_id by address (nodes are keyed by node_id;
         *     workers know only their own address) and hands the snapshot to the
         *     aggregator, which then treats poll results for that node as fallback while
         *     the push stays fresh. Unknown address → 404 (the worker retries once the
         *     controller has discovered / registered it).
         */
        post: operations["ingest_stats_api_fleet_ingest_stats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fleet Launch
         * @description Resolve targets, compute per-node rate, fan out POST /api/tests/start to
         *     every ONLINE target in parallel, persist a FleetRun, return the dispatch.
         */
        post: operations["fleet_launch_api_fleet_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/loops/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fleet Loops Launch
         * @description Resolve targets, compute per-node rate, fan out POST /api/loops to every
         *     ONLINE target in parallel, persist a FleetRun, return the dispatch.
         *
         *     Reuses the exact target-resolution + rate-splitting + FleetRun-persistence
         *     pattern as /api/fleet/launch; the only differences are the per-node payload
         *     (a StartLoopRequest) and that each result carries `campaign_id` rather than
         *     `test_id`.
         */
        post: operations["fleet_loops_launch_api_fleet_loops_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/loops/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fleet Loop View
         * @description Combined loop_stats across all member nodes of a loop fleet run.
         *
         *     Polls each member node's GET /api/loops/{campaign_id} for its latest
         *     loop_stats and sums minutes-out/in + completion across nodes (design §7
         *     stage 9). Per-node snapshots are echoed so the console can drill in.
         */
        get: operations["fleet_loop_view_api_fleet_loops__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/loops/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fleet Loops Stop
         * @description Best-effort stop of every member loop campaign in a fleet loop run.
         */
        post: operations["fleet_loops_stop_api_fleet_loops__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fleet Runs */
        get: operations["list_fleet_runs_api_fleet_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fleet Run */
        get: operations["get_fleet_run_api_fleet_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet Stats */
        get: operations["fleet_stats_api_fleet_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/stats/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet Stats History */
        get: operations["fleet_stats_history_api_fleet_stats_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fleet Stop
         * @description Best-effort stop of every member test in a fleet run.
         */
        post: operations["fleet_stop_api_fleet__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Group */
        put: operations["update_group_api_groups__group_id__put"];
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Controller health (unauthenticated, mirrors worker shape).
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Nodes */
        get: operations["list_nodes_api_nodes_get"];
        put?: never;
        /** Create Node */
        post: operations["create_node_api_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Node */
        put: operations["update_node_api_nodes__node_id__put"];
        post?: never;
        /** Delete Node */
        delete: operations["delete_node_api_nodes__node_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Node
         * @description Force an immediate health probe and return the refreshed NodeView.
         */
        post: operations["check_node_api_nodes__node_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ws Status */
        get: operations["ws_status_api_ws_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthSpec */
        AuthSpec: {
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * User
             * @default
             */
            user: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Password */
            password: string;
            /**
             * Role
             * @default operator
             */
            role: string;
            /** Username */
            username: string;
        };
        /** Destination */
        Destination: {
            /** Remote Host */
            remote_host: string;
            /**
             * Remote Port
             * @default 5060
             */
            remote_port: number;
            /**
             * Transport
             * @default udp
             */
            transport: string;
        };
        /** FleetLaunchRequest */
        FleetLaunchRequest: {
            auth?: components["schemas"]["AuthSpec"] | null;
            /** Call Limit */
            call_limit?: number | null;
            destination: components["schemas"]["Destination"];
            /** Duration */
            duration?: number | null;
            /** Group Id */
            group_id?: number | null;
            /** Max Calls */
            max_calls?: number | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Node Ids */
            node_ids?: number[] | null;
            /**
             * @default {
             *       "mode": "per_node",
             *       "value": 1
             *     }
             */
            rate: components["schemas"]["RateSpec"];
            /**
             * Scenario
             * @default basic_call
             */
            scenario: string;
        };
        /**
         * FleetLoopLaunchRequest
         * @description Fan-out launch of a Loop Campaign (design §4.4 / §7 stage 9).
         *
         *     Mirrors FleetLaunchRequest's target-resolution + rate-split contract, but
         *     fans out POST /api/loops (StartLoopRequest) to every ONLINE target instead of
         *     the one-shot /api/tests/start. `rate` is split exactly like a test launch
         *     (per_node | total). Per-call loop params map straight onto the worker's
         *     StartLoopRequest body.
         */
        FleetLoopLaunchRequest: {
            /**
             * Csv Path
             * @default
             */
            csv_path: string;
            destination: components["schemas"]["Destination"];
            /**
             * Duration Max S
             * @default 0
             */
            duration_max_s: number;
            /**
             * Duration Mode
             * @default fixed
             */
            duration_mode: string;
            /**
             * Duration S
             * @default 180
             */
            duration_s: number;
            /** Group Id */
            group_id?: number | null;
            /**
             * Match Key
             * @default exact
             */
            match_key: string;
            /**
             * Max Concurrent
             * @default 10
             */
            max_concurrent: number;
            /**
             * Name
             * @default
             */
            name: string;
            /** Node Ids */
            node_ids?: number[] | null;
            /**
             * @default {
             *       "mode": "per_node",
             *       "value": 1
             *     }
             */
            rate: components["schemas"]["RateSpec"];
            /**
             * Target Calls
             * @default 0
             */
            target_calls: number;
            /**
             * Target Minutes
             * @default 0
             */
            target_minutes: number;
        };
        /** FleetTrustBody */
        FleetTrustBody: {
            /**
             * Drop Untrusted
             * @default false
             */
            drop_untrusted: boolean;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Ips
             * @default []
             */
            ips: string[];
        };
        /** GroupCreate */
        GroupCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** GroupUpdate */
        GroupUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Node Ids */
            node_ids?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** NodeCreate */
        NodeCreate: {
            /** Address */
            address: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Group Id */
            group_id?: number | null;
            /** Name */
            name: string;
        };
        /** NodeUpdate */
        NodeUpdate: {
            /** Address */
            address?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Group Id */
            group_id?: number | null;
            /** Name */
            name?: string | null;
        };
        /** RateSpec */
        RateSpec: {
            /**
             * Mode
             * @default per_node
             */
            mode: string;
            /**
             * Value
             * @default 1
             */
            value: number;
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Password */
            password: string;
        };
        /** StatsIngestBody */
        StatsIngestBody: {
            /** Address */
            address: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: {
                x_api_key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_auth_users_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_auth_users_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_auth_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_auth_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fleet_trust_api_fleet_config_trust_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_fleet_trust_api_fleet_config_trust_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetTrustBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_stats_api_fleet_ingest_stats_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Fleet-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsIngestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_launch_api_fleet_launch_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetLaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_loops_launch_api_fleet_loops_launch_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetLoopLaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_loop_view_api_fleet_loops__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_loops_stop_api_fleet_loops__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fleet_runs_api_fleet_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fleet_run_api_fleet_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_stats_api_fleet_stats_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_stats_history_api_fleet_stats_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_stop_api_fleet__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_groups_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_groups_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_group_api_groups__group_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_nodes_api_nodes_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_node_api_nodes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_api_nodes__node_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_api_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_node_api_nodes__node_id__check_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ws_status_api_ws_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
